[package]
name = "pallet-randomness"
authors = { workspace = true }
description = "Provides randomness"
edition = "2018"
version = "0.1.0"

[dependencies]
frame-support = { workspace = true }
frame-system = { workspace = true }
environmental = { workspace = true }
log = { workspace = true }
nimbus-primitives = { workspace = true }
parity-scale-codec = { workspace = true, features = [ "derive" ] }
scale-info = { workspace = true, features = [ "derive" ] }
serde = { workspace = true, optional = true }
session-keys-primitives = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
schnorrkel = { workspace = true }
sp-consensus-babe = { workspace = true }

# Benchmarks
frame-benchmarking = { workspace = true, optional = true }
hex = { workspace = true }


[dev-dependencies]
derive_more = { workspace = true }
pallet-author-mapping = { workspace = true, features = [ "std" ] }
pallet-balances = { workspace = true, features = [ "std", "insecure_zero_ed" ] }

[features]
default = [ "std" ]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"hex/std",
	"nimbus-primitives/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde",
	"session-keys-primitives/std",
	"sp-core/std",
	"sp-consensus-babe/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"schnorrkel/std"
]
runtime-benchmarks = [
	"frame-benchmarking",
	"session-keys-primitives/runtime-benchmarks",
]
try-runtime = [ "frame-support/try-runtime" ]
