name: Cargo build
description: |
  Builds moonkit-template with given features.

inputs:
  features:
    description: features to include in the build (comma separated)
    required: false

runs:
  using: "composite"
  steps:
    - name: Rust Cache
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
    - name: Setup Variables
      shell: bash
      run: |
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
        # Set RUSTFLAGS if not already set
        if [ -z "$RUSTFLAGS" ]; then
          echo "RUSTFLAGS=-C opt-level=3 -D warnings -C linker=clang -C link-arg=-fuse-ld=$(pwd)/mold/bin/mold" >> $GITHUB_ENV
        fi
    - name: Setup Mold Linker
      shell: bash
      run: |
        mkdir -p mold
        curl -L --retry 10 --silent --show-error https://github.com/rui314/mold/releases/download/v2.40.4/mold-2.40.4-$(uname -m)-linux.tar.gz | tar -C $(realpath mold) --strip-components=1 -xzf -
    - name: Setup Rust toolchain
      shell: bash
      run: |
        rustup show
    - name: Build Node
      shell: bash
      run: |
        env
        params=" --locked --release -p moonkit-template"
        if [ -n "${{ github.event.inputs.features }}" ]; then
          params="$params --features ${{ github.event.inputs.features }}"
        fi
        echo "cargo build $params"
        cargo build $params
    - name: Display binary comments
      shell: bash
      run: readelf -p .comment ./target/release/moonkit-template
